apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-hydra-admin
  namespace: open-hydra

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-hydra-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: open-hydra-admin
    namespace: open-hydra

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: open-hydra-kube-system
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: open-hydra-admin
    namespace: open-hydra

---
apiVersion: v1
data:
  config.yaml: |
    podAllocatableLimit: -1
    defaultCpuPerDevice: 2000
    defaultRamPerDevice: 8192
    defaultGpuPerDevice: 0
    datasetBasePath: /mnt/public-dataset
    courseBasePath: /mnt/public-course
    workspacePath: /mnt/workspace
    defaultGpuDriver: nvidia.com/gpu
    gpuResourceKeys:
      - nvidia.com/gpu
      - amd.com/gpu
    serverIP: "localhost"
    patchResourceNotRelease: true
    disableAuth: true
    mysqlConfig:
      address: mycluster-instances.mysql-operator.svc
      port: 3306
      username: root
      password: openhydra
      databaseName: openhydra
      protocol: tcp
    leaderElection:
      leaderElect: false
      leaseDuration: 30s
      renewDeadline: 15s
      retryPeriod: 5s
      resourceLock: endpointsleases
      resourceName: open-hydra-api-leader-lock
      resourceNamespace: default
    authDelegateConfig:
      keystoneConfig:
        endpoint: http://keystone.openhydra.svc:5000
        username: admin
        password: admin
        domainId: default
kind: ConfigMap
metadata:
  name: open-hydra-config
  namespace: open-hydra

---
# deployment that mount configmap open-hydra-config to /etc/open-hydra/config.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-hydra-server
  namespace: open-hydra
  labels:
    app: open-hydra-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-hydra-api
  template:
    metadata:
      labels:
        app: open-hydra-api
    spec:
      serviceAccountName: open-hydra-admin
      containers:
        - name: open-hydra-api
          image: registry.cn-shanghai.aliyuncs.com/openhydra/open-hydra-server:latest
          imagePullPolicy: IfNotPresent
          command:
            [
              "open-hydra-server",
              "run",
              "--open-hydra-server-config",
              "/etc/open-hydra/config.yaml",
            ]
          ports:
            - containerPort: 443
          securityContext:
            privileged: true
          volumeMounts:
            - name: open-hydra-config
              mountPath: /etc/open-hydra/config.yaml
              subPath: config.yaml
            - name: dataset
              mountPath: /mnt/public-dataset
              mountPropagation: Bidirectional
            - name: course
              mountPath: /mnt/public-course
              mountPropagation: Bidirectional
            - name: workspace
              mountPath: /mnt/workspace
              mountPropagation: Bidirectional
      volumes:
        - name: open-hydra-config
          configMap:
            name: open-hydra-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: dataset
          hostPath:
            # This will mount the "/mnt/data" directory from the host node to the "/etc/nginx/conf.d" path in the container.
            path: /mnt/public-dataset
            type: Directory
        - name: course
          hostPath:
            # This will mount the "/mnt/data" directory from the host node to the "/etc/nginx/conf.d" path in the container.
            path: /mnt/public-course
            type: Directory
        - name: workspace
          hostPath:
            # This will mount the "/mnt/data" directory from the host node to the "/etc/nginx/conf.d" path in the container.
            path: /mnt/workspace
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: open-hydra-server
  namespace: open-hydra
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: https
      port: 443
      protocol: TCP
  selector:
    app: open-hydra-api
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.open-hydra-server.openhydra.io
spec:
  group: open-hydra-server.openhydra.io
  groupPriorityMinimum: 1000
  insecureSkipTLSVerify: true
  service:
    name: open-hydra-server
    namespace: open-hydra
    port: 443
  version: v1
  versionPriority: 15

---
apiVersion: v1
data:
  plugins: |
    {
        "defaultSandbox": "XEdu",
        "sandboxes": {
            "XEdu": {
                "cpuImageName": "registry.cn-shanghai.aliyuncs.com/openhydra/jupyter:Python-3.8.18-dual-lan",
                "gpuImageSet": {
                    "nvidia.com/gpu": "registry.cn-shanghai.aliyuncs.com/openhydra/jupyter:Python-3.8.18-dual-lan",
                    "amd.com/gpu": "registry.cn-shanghai.aliyuncs.com/openhydra/jupyter:Python-3.8.18-dual-lan"
                },
                "icon_name": "jupyter-lab.png",
                "command": [],
                "args": [],
                "description": "XEdu的全名为OpenXLabEdu，是基于OpenXLab的教育版，为上海人工智能实验室浦育团队开发的一套完整的AI开发和学习工具。XEdu核心工具为计算机视觉库MMEdu、神经网络库BaseNN和传统机器学习库BaseML，以及数据集处理工具BaseDT和通用模型推理工具XEduHub等。",
                "developmentInfo": [
                    "python-version: 3.8",
                    "jupyter-lab-version: 4.0.9",
                    "torch-version: 1.8.1+cu111",
                    "cuda-version: 11.1",
                    "lan: chinese | english"
                ],
                "ports": [
                  8888
                ],
                "volume_mounts": [
                    {
                        "name": "jupyter-lab",
                        "mount_path": "/root/notebook"
                    },
                    {
                        "name": "public-dataset",
                        "mount_path": "/root/notebook/dataset-public",
                        "read_only": true
                    },
                    {
                        "name": "public-course",
                        "mount_path": "/root/notebook/course-public",
                        "read_only": true
                    },
                    {
                        "name": "shm",
                        "mount_path": "/dev/shm",
                        "read_only": false
                    }
                ],
                "volumes": [
                    {
                      "host_path": {
                        "name": "jupyter-lab",
                        "path": "{workspace}/jupyter-lab/{username}",
                        "type": "DirectoryOrCreate"
                      }
                    },
                    {
                      "host_path": {
                        "name": "public-dataset",
                        "path": "{dataset-public}",
                        "type": "DirectoryOrCreate"
                      }
                    },
                    {
                      "host_path": {
                        "name": "public-course",
                        "path": "{course-public}",
                        "type": "DirectoryOrCreate"
                      }
                    },
                    {
                      "empty_dir": {
                        "name": "shm",
                        "medium": "Memory",
                        "size_limit": 2048
                      }
                    }
                ]
            },
            "Keras": {
                "cpuImageName": "registry.cn-shanghai.aliyuncs.com/openhydra/tensorflow:2.15.0-jupyter-cpu",
                "gpuImageSet": {
                    "nvidia.com/gpu": "registry.cn-shanghai.aliyuncs.com/openhydra/tensorflow:latest-gpu-with-jlab",
                    "amd.com/gpu": "registry.cn-shanghai.aliyuncs.com/openhydra/tensorflow:latest-gpu-with-jlab"
                },
                "icon_name": "keras.png",
                "command": [],
                "args": [],
                "description": "Keras是在谷歌TensorFlow的基础上发展起来的深度学习开发框架。可以把Keras看成是TensorFlow的入门简化版本，开发门槛更低，拥有大量的用户。",
                "developmentInfo": [
                    "keras-version: 2.6.1",
                    "tensorflow-version: 2.6.0",
                    "jupyter-lab-version: 4.0.9",
                    "lan: chinese | english"
                ],
                "ports": [
                  8888
                ],
                "volume_mounts": [
                    {
                        "name": "keras",
                        "mount_path": "/home/workspace"
                    },
                    {
                        "name": "public-dataset",
                        "mount_path": "/root/notebook/dataset-public",
                        "read_only": true
                    },
                    {
                        "name": "public-course",
                        "mount_path": "/root/notebook/course-public",
                        "read_only": true
                    }
                ],
                "volumes": [
                    {
                      "host_path": {
                        "name": "keras",
                        "path": "{workspace}/keras/{username}",
                        "type": "DirectoryOrCreate"
                      }
                    },
                    {
                      "host_path": {
                        "name": "public-dataset",
                        "path": "{dataset-public}",
                        "type": "DirectoryOrCreate"
                      }
                    },
                    {
                      "host_path": {
                        "name": "public-course",
                        "path": "{course-public}",
                        "type": "DirectoryOrCreate"
                      }
                    }
                ]
            },
            "PaddlePaddle": {
                "cpuImageName": "registry.cn-shanghai.aliyuncs.com/openhydra/paddle:2.6.0-jlab",
                "gpuImageSet": {
                    "nvidia.com/gpu": "registry.cn-shanghai.aliyuncs.com/openhydra/paddle:2.6.0-gpu-cuda12.0-cudnn8.9-trt8.6-jlab",
                    "amd.com/gpu": "registry.cn-shanghai.aliyuncs.com/openhydra/paddle:2.6.0-gpu-cuda12.0-cudnn8.9-trt8.6-jlab"
                },
                "icon_name": "PaddlePaddle.png",
                "command": [],
                "args": [],
                "description":"PaddlePaddle是百度开发的深度学习平台。PaddlePaddle集核心框架、基础模型库、端到端开发套件、丰富的工具组件、用户社区于一体，是中国首个自主研发、功能丰富、开源开放的产业级深度学习平台。",
                "developmentInfo": [
                    "PaddlePaddle-version: 2.1.0",
                    "jupyter-lab-version: 4.0.9",
                    "cuda-version: 12.0",
                    "lan: chinese | english"
                ],
                "ports": [
                  8888
                ],
                "volume_mounts": [
                    {
                        "name": "paddle",
                        "mount_path": "/home/workspace"
                    },
                    {
                        "name": "public-dataset",
                        "mount_path": "/root/notebook/dataset-public",
                        "source_path": "{dataset-public}",
                        "read_only": true
                    },
                    {
                        "name": "public-course",
                        "mount_path": "/root/notebook/course-public",
                        "source_path": "{course-public}",
                        "read_only": true
                    }
                ],
                "volumes": [
                    {
                      "host_path": {
                        "name": "paddle",
                        "path": "{workspace}/paddle/{username}",
                        "type": "DirectoryOrCreate"
                      }
                    },
                    {
                      "host_path": {
                        "name": "public-dataset",
                        "path": "{dataset-public}",
                        "type": "DirectoryOrCreate"
                      }
                    },
                    {
                      "host_path": {
                        "name": "public-course",
                        "path": "{course-public}",
                        "type": "DirectoryOrCreate"
                      }
                    }
                ]
            }
        }
    }
kind: ConfigMap
metadata:
  name: openhydra-plugin
  namespace: open-hydra
